version: '3.9'
services:
  metamorphosis-server:
    container_name: metamorphosis-server
    image: codebarbarian/metamorphosis-server:latest
    volumes:
      - ./src:/var/www/html/
    ports:
      - 80:80

  metamorphosis-database-server:
    container_name: metamorphosis-database-server-server
    image: codebarbarian/metamorphosis-database-server:latest
    volumes:
      - ./docker/metamorphosis-database-server-server/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=metamorphosis
      - MYSQL_USER=metamorphosis
      - MYSQL_PASSWORD=metamorphosis
      - MYSQL_ROOT_PASSWORD=metamorphosis
    ports:
      - 3306:3306